

<MainWidget>:
    BoxLayout:
        orientation: "vertical"

        FloatLayout:
            Label:
                text: "INPUT THE NUMBER TO BE SEARCH"
                pos: 180,170

            TextInput:
                id: inputs
                size_hint: 1, None
                height: "30dp"
                multiline: False
                pos: 180,150
                on_text_validate: root.on_enter()

<CustomPopup>:
    orientation: "vertical"
    Label:
        text: root.message